# Generated by Django 6.0.5 on 2026-05-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_records', to='citizons.person')),
            ],
        ),
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField()),
                ('divorce_date', models.DateField(blank=True, null=True)),
                ('marriage_place', models.CharField(max_length=200)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_marriages', to='citizons.person')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_marriages', to='citizons.person')),
            ],
        ),
        migrations.CreateModel(
            name='DivorceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divorce_date', models.DateField()),
                ('reason', models.CharField(choices=[('mutual', 'Mutual Consent'), ('cheating', 'Cheating'), ('abuse', 'Abuse'), ('financial', 'Financial Issues'), ('death', 'Death of Spouse'), ('other', 'Other')], max_length=50)),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marriage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divorce_record', to='marriage.marriagedetails')),
            ],
        ),
    ]
